CREATE TABLE 'bbs'. 'users' (
	id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	login_id VARCHAR(20) NOT NULL,
	password VARCHAR(255) NOT NULL,
	name VARCHAR(10) NOT NULL,
	branch_id INTEGER NOT NULL,
	position_id INTEGER NOT NULL,
	state TINYINT(1) NOT NULL
)

CREATE TABLE 'bbs'. 'branches' (
	id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL
)

CREATE TABLE 'bbs'. 'positions' (
	id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL
)

CREATE TABLE 'bbs'. 'postings' (
	id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	user_id INTEGER NOT NULL,
	title VARCHAR(50) NOT NULL,
	text VARCHAR(1000) NOT NULL,
	category VARCHAR(10) NOT NULL,
	insert_date TIMESTAMP NOT NULL,
	update_date TIMESTAMP NOT NULL
)

CREATE TABLE 'bbs'. 'comments' (
	id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	user_id INTEGER NOT NULL,
	posting_id INTEGER NOT NULL,
	text VARCHAR(500) NOT NULL,
	insert_date TIMESTAMP NOT NULL,
	update_date TIMESTAMP NOT NULL
)
